FROM tomcat:8.0.20-jre8

RUN rm -rf /usr/local/tomcat/webapps/*
COPY ROOT.war /usr/local/tomcat/webapps/

# RUN rm /usr/local/tomcat/conf/server.xml
# COPY sever.xml /usr/local/tomcat/conf/

# RUN rm /usr/local/tomcat/conf/context.xml
# COPY context.xml /usr/local/tomcat/conf/

EXPOSE $TOMCAT_HTTP_PORT

CMD ["catalina-dynamic-port.sh"]